ppe/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "ppe"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login, name="login"),
    path("detail", views.detail, name="detail"),
    path("set_geolocalisation", views.set_geolocalisation, name="geolocalisation"),
    path("check_geolocalisation", views.check_geolocalisation, name="check_geolocalisation"),
    path("contact_principal", views.contact_principal, name="contact_principal"),
    path("modification", views.modification, name="modification"),
    path("edit_geolocalisation", views.edit_geolocalisation, name="edit_geolocalisation"),
    path("edit_contacts", views.edit_contacts, name="edit_contacts"),
    path("edit_ppe_type", views.edit_ppe_type, name="edit_ppe_type"),
    path("soumission", views.soumission, name="soumission"),
    path("definition_type_dossier", views.definition_type_dossier, name="definition_type_dossier"),
    path("overview", views.overview, name="overview"),
    path("load_zipfile", views.load_zipfile, name="load_zipfile"),
    path("submit_for_validation", views.submit_for_validation, name="submit_for_validation"),
    path("admin_login", views.admin_login, name="admin_login"),
    path("admin_logout", views.admin_logout, name="admin_logout"),
    path("zip_status", views.zip_status, name="zip_status"),
    path("get_final_documents", views.get_final_documents, name="get_final_documents"),
]

ppe/models.py
import os

from django.core.validators import FileExtensionValidator
from django.contrib.gis.db import models
from django.utils.timezone import now
from django.conf import settings


def unique_folder_path(instance, filename):
    """ Define the new storage path from login_code
        and prefix the uploaded files with the date
    """
    date_prefix = now().strftime('%Y%m%d_%H%M%S')
    new_filename = f"{date_prefix}.zip"
    return '/'.join(["ppe", f"{instance.dossier_ppe.id}", new_filename])

def rename_pdf_accord(instance, filename):
    """ Define the new filename using a date prefix
    """
    date_prefix = now().strftime('%Y%m%d_%H%M%S')
    new_filename = f"{date_prefix}_{filename}"
    return '/'.join(['ppe', 'confirmations', new_filename])

class Geolocalisation(models.Model):
    geom = models.PointField(srid=settings.DEFAULT_SRID)

    class Meta:
        db_table = 'ppe\".\"geolocalisation'


class AdresseFacturation(models.Model):
    type_personne = models.CharField(
        choices=(
            ("pp", "Personne physique"),
            ("pm", "Personne morale")
              ),
                max_length=50, default="pp")
    nom_raison_sociale = models.CharField(max_length=150)
    prenom = models.CharField(max_length=100)
    complement = models.CharField(max_length=100, blank=True)
    rue = models.CharField(max_length=100)
    no_rue = models.CharField(max_length=10, blank=True)
    npa = models.IntegerField()
    localite = models.CharField(max_length=100)
    file = models.FileField(upload_to=rename_pdf_accord, validators=[
        FileExtensionValidator(["pdf"])
    ])

    def __str__(self):
        return self.nom_raison_sociale

    def filename(self):
        return os.path.basename(self.file.name)

    class Meta:
        ordering = ["nom_raison_sociale"]
        db_table = 'ppe\".\"adresse_facturation'
        verbose_name = "Adresse facturation"
        verbose_name_plural = "Adresses facturation"


class ContactPrincipal(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    no_tel = models.CharField(max_length=15)
    raison_sociale = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.nom + str(' ') + self.prenom

    class Meta:
        ordering = ["nom"]
        db_table = 'ppe\".\"contact_principal'
        verbose_name = "Contact principal"
        verbose_name_plural = "Contacts principaux"


class Notaire(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    complement = models.CharField(max_length=100, blank=True)
    rue = models.CharField(max_length=100)
    no_rue = models.CharField(max_length=10, blank=True)
    npa = models.IntegerField()
    localite = models.CharField(max_length=100)

    def __str__(self):
        return self.nom + str(' ') + self.prenom

    class Meta:
        ordering = ["nom"]
        db_table = 'ppe\".\"notaire'
        verbose_name = "Notaire"
        verbose_name_plural = "Notaires"


class Signataire(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    complement = models.CharField(max_length=100, blank=True)
    rue = models.CharField(max_length=100)
    no_rue = models.CharField(max_length=10, blank=True)
    npa = models.IntegerField()
    localite = models.CharField(max_length=100)

    def __str__(self):
        return self.nom + str(' ') + self.prenom

    class Meta:
        ordering = ["nom"]
        db_table = 'ppe\".\"signataire'
        verbose_name = "Signataire"
        verbose_name_plural = "Signataires"


class DossierPPE(models.Model):
    class DossierStatut(models.TextChoices):
        P = "P", "En préparation"
        S = "S", "Soumis"
        T = "T", "En traitement"
        C = "C", "Corrections requises"
        R = "R", "Rejeté"
        V = "V", "Dossier papier validé"

    class TypeDossier(models.TextChoices):
        C = "C", "Constitution"
        R = "R", "Révision"
        M = "M", "Modification"
        I = "I", "Indéfini"
             
    login_code = models.CharField(max_length=16)
    cadastre = models.CharField(max_length=50)
    numcad = models.IntegerField()
    nummai = models.CharField(max_length=10)
    coord_E = models.IntegerField()
    coord_N = models.IntegerField()
    statut = models.CharField(
        max_length=20,
        choices=DossierStatut.choices,
        default=DossierStatut.P)
    type_dossier = models.CharField(
        max_length=20,
        choices=TypeDossier.choices,
        default=TypeDossier.I)
    revision_jouissances = models.CharField(max_length=3, default=None, blank=True, null=True)
    elements_rf_identiques = models.CharField(max_length=3, default=None, blank=True, null=True)
    nouveaux_droits = models.CharField(max_length=3, default=None, blank=True, null=True)
    ref_geoshop = models.CharField(max_length=20, default=None, blank=True, null=True)
    ref_dossier_initial = models.IntegerField(null=True)
    contact_principal = models.ForeignKey(ContactPrincipal, on_delete=models.CASCADE)
    signataire = models.ForeignKey(Signataire, on_delete=models.CASCADE)
    notaire = models.ForeignKey(Notaire, on_delete=models.CASCADE)
    adresse_facturation = models.ForeignKey(AdresseFacturation, on_delete=models.CASCADE)
    aff_infolica = models.IntegerField(default=0,null=True)
    date_creation = models.DateTimeField("Date de création", auto_now=True)
    date_soumission = models.DateTimeField("Date de soumission", auto_now=True, blank=True)
    date_validation = models.DateTimeField("Date de validation", auto_now=True, blank=True)
    geom = models.PointField(srid=settings.DEFAULT_SRID)
    
    class Meta:
        db_table = 'ppe\".\"dossier_ppe'
        verbose_name = "Dossier PPE"
        verbose_name_plural = "Dossiers PPE"

class Zipfile(models.Model):
    class FileStatut(models.TextChoices):
        CAA = "CAA", "Contrôle automatique : archivé"
        CAC = "CAC", "Contrôle automatique : en cours"
        CAE = "CAE", "Contrôle automatique : erreurs à corriger"
        ERR = "ERR", "Contrôle automatique : erreur interne"
        CAV = "CAV", "Contrôle automatique : validé"
        CMS = "CMS", "Contrôle manuel : en cours "
        CMC = "CMC", "Contrôle manuel : en cours"
        CME = "CME", "Contrôle manuel : erreurs à corriger"
        CMV = "CMV", "Contrôle manuel : validé"
        DPV = "DPV", "Dossier papier validé"

    zipfile = models.FileField(upload_to=unique_folder_path, validators=[
        FileExtensionValidator(["zip"])
    ])
    upload_date = models.DateTimeField("Date de chargement", auto_now=True)
    file_statut = models.CharField(
        max_length=3,
        choices=FileStatut.choices,
        default=FileStatut.CAC,
    )
    dossier_ppe = models.ForeignKey(DossierPPE, on_delete=models.CASCADE, related_name="zipfiles", blank=True)

    class Meta:
        ordering = ["-upload_date"]
        db_table = 'ppe\".\"zipfile'

    def filename(self):
        return os.path.basename(self.zipfile.name)


class GeoshopCadastreOrder(models.Model):
    date_ordered = models.DateTimeField()
    date_processed = models.DateTimeField()
    geom = models.PolygonField(srid=settings.DEFAULT_SRID)

    class Meta:
        managed = False
        db_table = 'ppe_static\".\"geoshop_order'

ppe/templates/ppe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'ppe/style.css' %}">
    <link href="https://sitn.ne.ch/sitnstatic/sitn-bootstrap@v5.2.3/sitn-bootstrap.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>

    <title>{% block titre %} {% endblock titre %}</title>
    {% block head %}
      {{ form.media }}
    {% endblock head %}

    <script src="{% static 'js/utils.js' %}"></script>
</head>
<body>

  <!-- Header -->
  <header class="row w-100 m-0 align-items-center">
    <div id="home" class="entete text-center col-lg-9 col-md-9 col-sm-8 col-7">
      <!-- a class="home link-underline-opacity-0" href="{% url 'ppe:index' %}">
        <i class="bi bi-house-fill navbar-brand" style="color:white;"></i>
      </a //-->
      <a class="home link-underline link-underline-opacity-0" href="{% url 'ppe:index' %}">
        Contrôle des dossiers PPE
      </a>
    </div>
    <div id="drapeau" class="drapeau col-lg-3 col-md-3 col-sm-4 col-5 text-end">
      <a href="https://www.ne.ch/autorites/DDTE/SGRF/Pages/accueil.aspx" target="_new">
        <img src="{% static 'images/logo_ne_negatif.png' %}" alt="Drapeau du canton NE" />
      </a>
    </div>
  </header>

  <!-- Main Container -->
  <div class="container-fluid">
    <div class="row main-container">

      <!-- Sidebar -->
      <aside class="col-12 col-md-2 sidebar position-relative align-items-end">
        <!-- Collapse toggle button -->
        <button class="btn btn-outline-secondary toggle-btn d-sm-none" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarLinks" aria-expanded="false" aria-controls="sidebarLinks">
          ☰ Menu
        </button>

        <!-- Collapsible Nav -->
        <div class="collapse d-md-block" id="sidebarLinks">
          <nav class="nav flex-column sidebar-nav position-fixed bottom-0 start-0">
            <h6 class="fw-bold ps-3 mb-2">Liens utiles</h6>
            <a class="nav-link nav-item" href="https://www.ne.ch/autorites/DDTE/SGRF/mensuration/Pages/propriete_par_etages.aspx" target="_new">PPE | Page internet</a>
            <a class="nav-link nav-item" href="https://www.ne.ch/autorites/DDTE/SGRF/mensuration/Documents/Directive_PPE_PROVISOIRE.pdf" target="_new">PPE | Directive</a>
            <a class="nav-link nav-item" href="https://www.ne.ch/autorites/DDTE/SGRF/mensuration/Documents/Annexe1_Preparation_fichiers_vectoriels_PROVISOIRE.pdf" target="_new">PPE | Annexe 1 : préparation<br> des fichiers vectoriels</a>
            <a class="nav-link nav-item" href="https://www.ne.ch/autorites/DDTE/SGRF/mensuration/Documents/PPE%202020/PPE_Lettre_Type.docx"  target="_new">PPE | Modèle : accord de prise<br> en charge des frais</a>
            <a class="nav-link nav-item" href="https://www.ne.ch/autorites/DDTE/SGRF/mensuration/Pages/propriete_par_etages.aspx" target="_new">PPE | Exemples</a>
            <a class="nav-link nav-item" href="https://sitn.ne.ch/geoshop" target="shop">Géoshop</a>
            <!-- a class="nav-link nav-item" href="#">Registre des architectes<br> et ingénieurs</a //-->
            <a class="nav-link nav-item" href="mailto:sgrf.ppe@ne.ch?Subject=Dossier PPE">Nous contacter</a>
            <a class="nav-link nav-item" href="{% url 'ppe:admin_login' %}">Login</a>
          </nav>
        </div>
      </aside>

      <!-- Content Area -->
      <main class="col-12 col-md-10 content p-4">
        {% block content %}
        {% endblock content %}

        {% block footer %}
        <footer class="mt-4 pt-2 text-muted">
            {% if user.is_authenticated %}<a class="nav-item" href="{% url 'ppe:admin_logout' %}">Logout</a> -{% endif %} PPE NUMERIQE v0.9b
        </footer>
        {% endblock footer %}
      </main>

    </div>
  </div>

</body>
</html>

ppe/templates/ppe/email_new_case_creation.html
{% autoescape off %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width" />
  <style>
    body {
      width: 100% !important;
      min-width: 100%;
      margin: 0;
      padding: 0;
    }

    table {
      width: 100% !important;
      border-spacing: 0;
      border-collapse: collapse;
    }


    td {
      padding: 0;
      text-align: left;
      word-break: break-word;
      -webkit-hyphens: auto;
      -moz-hyphens: auto;
      hyphens: auto;
      border-collapse: collapse !important;
    }

    table,
    td {
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }

    body,
    table,
    td,
    p,
    a,
    li,
    blockquote {
      -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
    }

    body {
      color: #212121;
      font-family: "Helvetica Neue", Helvetica, Arial, Verdana, "Trebuchet MS";
      font-weight: 400;
      font-size: 18px;
      line-height: 1.429;
      letter-spacing: 0.001em;
      background-color: #FFF;
    }

    .header {
      background: #26a59a;
      color: #fff;
      font-weight: bold;
    }

    td {
      padding: 25px;
    }

    .footer {
      font-size: 12px;
      background: #eee;
    }

    .footer td {
      text-align: center;
    }
  </style>
</head>

<body>
    <p>Vous venez de créer un nouveau dossier PPE sur l'application de gestion des PPE numériques</p>
        <p>Cadastre : {{ doc.cadastre}}<br>
            Bien-fonds : {{ doc.nummai }}<br>
            Type de dossier : {{ doc.get_type_dossier_display }}</p>
        <p>Son code unique de connexion est  :</p> <h2 id="login_code">{{ doc.login_code }}</h2> <p><b>Attention :</b>
            Gardez bien ce code, vous en avez besoin pour tout changement.</p>
        <p>Rendez-vous sur <a href="https://sitn.ne.ch/apps/ppe" target="_blank ">https://sitn.ne.ch/apps/ppe</a>
        pour gérer votre dossier.
        <p>
          Ceci est un mail automatique, prière de ne pas y répondre. Pour toute question n'hésitez pas à nous contacter
          à l'adresse <a href="mailto:sgrf.ppe@ne.ch">sitn@ne.ch</a>.
        </p>
</body>

</html>
{% endautoescape %}

ppe/templates/ppe/index.html
{% extends 'ppe/base.html' %}

{% block titre %}
Application de gestion des PPE
{% endblock titre %}

{% block content %}
      
        <h3>Bienvenue sur l’application de contrôle des dossiers PPE par le SGRF</h3>

        <p><br></p>
        <h5>Que souhaitez-vous faire?</h5>
        <br>
        <div>
                <a href="{% url 'ppe:geolocalisation' %}" class="button-lg btn btn-success">Nouvelle soumission</a>
                <i id="info2" class="bi bi-info-circle-fill" style="color: cornflowerblue;"></i>
                <div id="info_soumission">Soumettre un dossier de constitution,<br> de modification 
                    ou de révision de PPE<br> pour la première fois.</div>

                <a href="{% url 'ppe:overview' %}" class="button-lg btn btn-success">Modifier une soumission</a>
                <i id="info1" class="bi bi-info-circle-fill" style="color: cornflowerblue;"></i>
                <div id="info_modification">Modifier les informations<br> d'un dossier déjà soumis.</div>
        </div>
        {% if user.is_authenticated %}
            {% if latest_dossiers_list %}
            <div id="admin_list">
                <br>

                <table width="100%" class="table table-striped caption-top">
                    <caption>Admin: Liste des dossiers PPE en cours</caption>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Cadastre</th>
                        <th>No. bien-fonds</th>
                        <th>Date création</th>
                        <th>Type dossier</th>
                        <th>Statut dernier zip</th>
                        <th>Code</th>
                    </tr>
                    </thead>
                    <tbody>
                {% for dossierppe in latest_dossiers_list %}
                    <tr>
                        <td>{{ dossierppe.id }}</td>
                        <td>{{ dossierppe.cadastre }}</td>
                        <td>{{ dossierppe.nummai }}</td>
                        <td>{{ dossierppe.date_creation }}</td>
                        <td>{{ dossierppe.get_type_dossier_display }}
                            {% if dossierppe.get_type_dossier_display == 'Modification' %}
                            (Réf. initiale: <a href="{% url 'admin:index' %}ppe/dossierppe/{{ dossierppe.ref_dossier_initial }}" target="_new">{{ dossierppe.ref_dossier_initial }}</a>)
                            {% endif %}
                        </td>
                        <td>{{ dossierppe.zipfiles.first.get_file_statut_display }}</td>
                        <td><a href="{% url 'ppe:modification' %}">{{ dossierppe.login_code }}</a></td>
                    </tr>
                {% empty %}
                    <p>Aucun dossier n'a été trouvé.</p>
                {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        {% endif %}
        </div>

{% endblock content %}

ppe/templates/ppe/overview.html
{% extends 'ppe/base.html' %}

{% block titre %}
Dépôt d'un dossier - Récapitulatif
{% endblock titre %}

{% block content %}

    {% if error_message %}<p class="alert alert-danger"><strong>{{ error_message }}</strong></p>{% endif %}

    {% if dossier_ppe %}
    <h3>Récapitulatif</h3>

    <div class="row m-0">
        <div class="col-6">
            <section>
                <br>
                <table width="100%">
                <tr>
                    <th class="fs-4" width="50%">Localisation</th>
                    <th>{% if dossier_ppe.statut in 'S,C' %}<button type="button" disabled class="btn btn-secondary">Modifier</button>{% else %}
                        <a href="{% url 'ppe:edit_geolocalisation' %}" class="btn btn-success">Modifier</a>{% endif %}</th>
                </tr>
                <tr><td>Cadastre</td><td><b>{{ dossier_ppe.cadastre }}</b></td></tr>
                <tr><td>Bien-fonds</td><td><b>{{ dossier_ppe.nummai }}</b></td></tr>
                </table>
            </section>

            <section>
                <br><br>
                <table width="100%">
                <tr>
                    <th class="fs-4" width="50%">Contacts</th>
                    <th>{% if dossier_ppe.statut in 'S,C' %}<button type="button" disabled class="btn btn-secondary">Modifier</button>{% else %}
                        <a href="{% url 'ppe:edit_contacts' %}" class="btn btn-success">Modifier</a>{% endif %}</th>
                </tr>
                    <td colspan="2" class="fs-5 fw-bold">Personne de contact</td>
                <tr>
                    <td colspan="2">{{ dossier_ppe.contact_principal.nom}} {{ dossier_ppe.contact_principal.prenom }}</td>
                </tr><tr>
                        {%if dossier_ppe.contact_principal.raison_sociale %}
                        <td colspan="2" >{{ dossier_ppe.contact_principal.raison_sociale }}</td>
                        {% endif %}
                </tr><tr>
                        <td colspan="2" >{{ dossier_ppe.contact_principal.no_tel }}</td>
                </tr><tr>
                        <td colspan="2" >{{ dossier_ppe.contact_principal.email }}</td>
                </tr>
                </table>
            </section>

            <section>        
                <p class="fs-5 fw-bold">Notaire</p>
                <p>
                    Me {{ dossier_ppe.notaire.nom}} {{ dossier_ppe.notaire.prenom }}</br>
                    {%if dossier_ppe.notaire.raison_sociale %}
                    {{ dossier_ppe.notaire.raison_sociale }}</br>
                    {% endif %}
                    {%if dossier_ppe.notaire.complement %}
                    {{ dossier_ppe.notaire.complement }}</br>
                    {% endif %}
                    {{ dossier_ppe.notaire.rue }} {{ dossier_ppe.notaire.no_rue }}</br>
                    {{ dossier_ppe.notaire.npa }} {{ dossier_ppe.notaire.localite }}</br>
                </p>
            </section>

            <section>
                <p class="fs-5 fw-bold">Signataire</p>
                <p>
                    {{ dossier_ppe.signataire.nom}} {{ dossier_ppe.signataire.prenom }}</br>
                    {%if dossier_ppe.signataire.raison_sociale %}
                    {{ dossier_ppe.signataire.raison_sociale }}</br>
                    {% endif %}
                    {%if dossier_ppe.signataire.complement %}
                    {{ dossier_ppe.signataire.complement }}</br>
                    {% endif %}
                    {{ dossier_ppe.signataire.rue }} {{ dossier_ppe.signataire.no_rue }}</br>
                    {{ dossier_ppe.signataire.npa }} {{ dossier_ppe.signataire.localite }}</br>
                </p>
            </section>

            <section>
                <p class="fs-5 fw-bold">Adresse de facturation</p>
                <p>
                    {{ dossier_ppe.adresse_facturation.nom_raison_sociale}} {{ dossier_ppe.adresse_facturation.prenom }}</br>
                    {%if dossier_ppe.adresse_facturation.complement %}
                    {{ dossier_ppe.adresse_facturation.complement }}</br>
                    {% endif %}
                    {{ dossier_ppe.adresse_facturation.rue }} {{ dossier_ppe.adresse_facturation.no_rue }}</br>
                    {{ dossier_ppe.adresse_facturation.npa }} {{ dossier_ppe.adresse_facturation.localite }}</br>
                    <i>Fichier actuel : {{ dossier_ppe.adresse_facturation.file.name }}</br></i>
                </p>
            </section>
        </div>
                
        {%if dossier_ppe.type_dossier %}
        <div class="col-6">
            <section>
            <br>
            <table width="100%">
            <tr>
                <th class="fs-4" width="50%">Type de dossier</th>
                    <th>{% if dossier_ppe.statut in 'S,C' %}<button type="button" disabled class="btn btn-secondary">Modifier</button>{% else %}
                        <a href="{% url 'ppe:edit_ppe_type' %}" class="btn btn-success">Modifier</a>{% endif %}</th>
            </tr>
                {% if dossier_ppe.type_dossier == 'C' %}
            <tr>
                <td>Type de dossier :</td><td>{{ dossier_ppe.get_type_dossier_display }}</td>
            </tr>
            <tr>
                <td>Réf. géoshop:</td>
                <td>{{ dossier_ppe.ref_geoshop }}</td>
            </tr>
                {% elif dossier_ppe.type_dossier == 'R' %}
            <tr>
                <td>Type de dossier :</td><td>Révision</td>
            </tr>
            <tr>
                <td>La révision concerne uniquement des droits de jouissance</td>
                <td>{{ dossier_ppe.revision_jouissances }}</td>
            </tr>
            <tr>
                <td>La situation cadastrale reste identique</td>
                <td>{{ dossier_ppe.elements_rf_identiques }}</td>
            </tr>
                    {% if dossier_ppe.elements_rf_identiques == 'oui' %}
            <tr>
                <td colspan="2" class="alert alert-danger">Il n'est pas nécessaire de fournir les couches/calque 101 à 106 (voir 
              <a href="https://www.ne.ch/autorites/DDTE/SGRF/mensuration/Documents/Annexe1_Preparation_fichiers_vectoriels_PROVISOIRE.pdf" target="_new">
                annexe 1
              </a>).</td>
            </tr>
                    {% elif dossier_ppe.elements_rf_identiques == 'non' %}
            <tr>
                <td>Réf. géoshop:</td>
                <td>{{ dossier_ppe.ref_geoshop }}</td>
            </tr>
                    {% endif %}
                {% elif dossier_ppe.type_dossier == 'M' %}
            <tr>
                <td class="pb-3">Type de dossier :</td><td>Modification</td>
            </tr>
            <tr>
                <td colspan="2" class="alert alert-secondary">
                <h6>Dossier d'origine</h6>
                    {% if dossier_initial.id %}
                    <table width="100%">
                        <tr>
                            <td>Type de dossier :</td><td>{% if dossier_initial.type_dossier == 'C' %}Constitution{% else %}Révision{% endif %}</td>
                        </tr>
                        {% if dossier_initial.ref_geoshop %}
                        <tr>
                            <td>Référence geoshop :</td><td>{{ dossier_initial.ref_geoshop }}</td>
                        </tr>
                        {% endif %}
                        {% if dossier_initial.type_dossier == 'R' %}
                        <tr>
                            <td>La révision concerne uniquement des droits de jouissance :</td><td>{{ dossier_ppe.revision_jouissances }}</td>
                        <tr>
                            <td>La situation cadastrale reste identique :</td><td>{{ dossier_ppe.elements_rf_identiques }}</td>
                        </tr>
                        {% endif %}
                    </p>
                    </table>
                    {% else %}
                <p>Une erreur avec la référence du dossier d'origine est survenue.</p>
                    {% endif%}
                </td>
            </tr>
                {% endif %}
            </table>
            </section>
            {% endif %}

            <section>
                <br><br>
                {% for zip in dossier_ppe.zipfiles.all %}
                <table width="100%">
                {% if forloop.first %}
                    <tr>
                        <th class="fs-4" width="50%">Chargement des fichiers</th>
                        <th>{% if not zip.file_statut in 'CAC, CAE, CME' %}
                            <button type="button" disabled class="btn btn-secondary">Ajouter</button>{% else %}
                            <a href="{% url 'ppe:load_zipfile' %}" class="btn btn-success">Ajouter</a></th>{% endif %}
                    </tr>
                    </table>
                    <table width="100%">
                    <thead>
                    <tr>
                        <th width="30%" style="padding-top: 20px;">Date et heure</th><th style="padding-top: 20px;">Statut</th>
                    </tr>
                    </thead>
                    <tbody
                        id="zip-status-block"
                        hx-get="{% url 'ppe:zip_status' %}"
                        hx-trigger="load, every 60s"
                        hx-swap="innerHTML"
                    >
                        {% include "ppe/zip_status.html" %}
                    </tbody>
                    {% if dossier_ppe.zipfiles.all|length > 1 %}
                    <tr>
                        <th colspan="2" style="padding-top: 25px;">Historique</th>
                    </tr>
                    {% endif %}
                {% else %}
                    <tr>
                        <td width="30%" style="padding-left: 10px;">{{ zip.upload_date }}</td>
                        <td style="text-align: left;">{{ zip.get_file_statut_display }}</td>
                    </tr>
                {% endif %}
                </table>
            </section>
            {% empty %}
        </div>
            <div class="row m-0">
                <form id="overview_form" class="form-horizontal" action="soumission" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Continuer" class="valider btn btn-success">
                </form>
            {% endfor %}
    </div>

    {% else %}
    <p>Une erreur inconnue est survenue</p>
    {% endif %}

{% endblock content %}